import fitz
import faiss
import numpy as np
import requests
from sentence_transformers import SentenceTransformer
import re
import os
import sys
from dotenv import load_dotenv
import shutil
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def markdown_to_html(text):
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    text = re.sub(r'\*\*(.*?)\*\*|__(.*?)__', lambda m: f"<b>{m.group(1) or m.group(2) or ''}</b>", text)
    text = re.sub(r'\*(.*?)\*|_(.*?)_', lambda m: f"<i>{m.group(1) or m.group(2) or ''}</i>", text)
    return text

def parse_study_guide(text):
    target_headings = [
        ("Chapter Syllabus (Topics Covered)", ["chapter syllabus", "topics covered"]),
        ("Important Topics to Master", ["important topics to master", "important topics"]),
        ("Career-Oriented Topics", ["career-oriented topics", "career oriented topics", "careeroriented topics"]),
        ("Chapter Summary", ["chapter summary", "summary"]),
        ("Key Takeaways", ["key takeaways", "takeaways"]),
        ("Teaching Plan (Instructor Guide)", ["teaching plan", "instructor guide"])
    ]
    
    lines = text.split('\n')
    sections = []
    
    current_title = "Header"
    current_content = []
    
    for line in lines:
        stripped = line.strip()
        clean_line = re.sub(r'[*#_\-]', '', stripped).strip().lower()
        matched_heading = None
        for display_title, patterns in target_headings:
            if any(p in clean_line for p in patterns):
                if len(clean_line) < 60:
                    matched_heading = display_title
                    break
        
        if matched_heading:
            if current_content or current_title != "Header":
                clean_content_lines = []
                for l in current_content:
                    l_strip = l.strip()
                    if l_strip and (all(c == '-' for c in l_strip) or all(c == '=' for c in l_strip)) and len(l_strip) >= 5:
                        continue
                    clean_content_lines.append(l)
                
                sections.append({
                    'title': current_title,
                    'content': '\n'.join(clean_content_lines).strip()
                })
            current_title = matched_heading
            current_content = []
        else:
            current_content.append(line)
            
    if current_content or current_title != "Header":
        clean_content_lines = []
        for l in current_content:
            l_strip = l.strip()
            if l_strip and (all(c == '-' for c in l_strip) or all(c == '=' for c in l_strip)) and len(l_strip) >= 5:
                continue
            clean_content_lines.append(l)
        sections.append({
            'title': current_title,
            'content': '\n'.join(clean_content_lines).strip()
        })
        
    return sections


def draw_page_number(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#718096'))
    canvas.setStrokeColor(colors.HexColor('#E2E8F0'))
    canvas.setLineWidth(0.5)
    canvas.line(54, 55, doc.width + 54, 55)
    canvas.drawString(54, 40, "Generated by AI Teaching Assistant")
    canvas.drawRightString(doc.width + 54, 40, f"Page {doc.page}")
    canvas.restoreState()

def draw_header_footer(canvas, doc):
    draw_page_number(canvas, doc)
    canvas.saveState()
    canvas.setFont('Helvetica-Bold', 8)
    canvas.setFillColor(colors.HexColor('#4F46E5'))
    canvas.drawString(54, 750, "AI TEACHING ASSISTANT - TEACHING PLAN & GUIDE")
    canvas.setStrokeColor(colors.HexColor('#E2E8F0'))
    canvas.setLineWidth(0.5)
    canvas.line(54, 740, doc.width + 54, 740)
    canvas.restoreState()

def create_horizontal_rule():
    t = Table([['']], colWidths=['100%'], rowHeights=[2])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#E2E8F0')),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    return t

def create_section_heading(title, styles):
    p = Paragraph(f"<b>{title}</b>", ParagraphStyle(
        'SideHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#1A365D'),
        keepWithNext=True
    ))
    t = Table([[p]], colWidths=['100%'])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING', (0,0), (-1,-1), 8),
        ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ('LINELEFT', (0,0), (0,-1), 4, colors.HexColor('#4F46E5')),
    ]))
    return t

def process_section_lines(content_text, styles):
    flowables = []
    lines = content_text.split('\n')
    current_paragraph = []
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14.5,
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=6
    )
    
    bullet_style = ParagraphStyle(
        'CustomBullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14.5,
        textColor=colors.HexColor('#2D3748'),
        leftIndent=20,
        firstLineIndent=-10,
        spaceAfter=4
    )
    
    nested_bullet_style = ParagraphStyle(
        'CustomNestedBullet',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor('#4A5568'),
        leftIndent=35,
        firstLineIndent=-10,
        spaceAfter=4
    )
    
    def flush_paragraph():
        if current_paragraph:
            text = ' '.join(current_paragraph).strip()
            text = re.sub(r'\s+', ' ', text)
            if text:
                html_text = markdown_to_html(text)
                flowables.append(Paragraph(html_text, body_style))
            current_paragraph.clear()
            
    prefixes = ('• ', '* ', '- ', '•\t', '*\t', '-\t')
    for line in lines:
        stripped = line.strip()
        if not stripped:
            flush_paragraph()
            if flowables and not isinstance(flowables[-1], Spacer):
                flowables.append(Spacer(1, 6))
            continue
            
        if stripped.startswith(prefixes) or stripped in ('•', '*', '-'):
            flush_paragraph()
            has_leading_space = len(line) - len(line.lstrip()) > 0
            bullet_content = stripped[2:] if stripped.startswith(prefixes) else ''
            html_text = markdown_to_html(bullet_content.strip())
            
            if has_leading_space:
                flowables.append(Paragraph(f"&bull; {html_text}", nested_bullet_style))
            else:
                flowables.append(Paragraph(f"&bull; {html_text}", bullet_style))
        else:
            current_paragraph.append(line)
            
    flush_paragraph()
    return flowables

def generate_pdf(answer, question, matched_sec=None):
    parsed_sections = parse_study_guide(answer)
    
    chapter_num = "Not Available"
    chapter_name = "Not Available"
    
    header_sec = next((s for s in parsed_sections if s['title'] == 'Header'), None)
    if header_sec:
        for line in header_sec['content'].split('\n'):
            if line.lower().startswith("chapter number:"):
                chapter_num = line.split(":", 1)[1].strip()
            elif line.lower().startswith("chapter name:"):
                chapter_name = line.split(":", 1)[1].strip()
                
    if matched_sec:
        if chapter_num == "Not Available":
            chapter_num = matched_sec.get('number', 'Not Available')
        if chapter_name == "Not Available":
            chapter_name = matched_sec.get('name', 'Not Available')
            
    if chapter_num == "Not Available" and chapter_name == "Not Available":
        chapter_name = question
        
    pdf_filename = "teaching_plan.pdf"
    
    doc = SimpleDocTemplate(
        pdf_filename,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    story = []
    styles = getSampleStyleSheet()
    
    title_top = Paragraph("AI TEACHING ASSISTANT", ParagraphStyle(
        'TitleTop',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=12,
        textColor=colors.HexColor('#4F46E5'),
        spaceAfter=4
    ))
    story.append(title_top)
    
    title_text = f"Chapter {chapter_num}: {chapter_name}" if chapter_num != "Not Available" else chapter_name
    title_main = Paragraph(title_text, ParagraphStyle(
        'TitleMain',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1A365D'),
        spaceAfter=10
    ))
    story.append(title_main)
    story.append(create_horizontal_rule())
    story.append(Spacer(1, 15))
    
    for section in parsed_sections:
        if section['title'] == 'Header' or not section['title'].strip():
            continue
            
        story.append(create_section_heading(section['title'], styles))
        story.append(Spacer(1, 6))
        
        section_flowables = process_section_lines(section['content'], styles)
        story.extend(section_flowables)
        story.append(Spacer(1, 12))
        
    doc.build(story, onFirstPage=draw_page_number, onLaterPages=draw_header_footer)
    return pdf_filename